spring:
  application:
    name: activities
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://47.122.51.163:3306/activities_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8&allowMultiQueries=true
    username: root
    password: ECS_mysql_password
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: SPHHikariPool
  servlet:
    multipart:
      max-file-size: 50MB # 传输文件大小配置
  data:
    redis:
      host: 47.122.51.163
      port: 6379
      database: 0

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true

# 日志配置
logging:
  level:
    com:
      xidian:
        activities:
          mapper: debug

# java后端端口
server:
  port: 8080

# minio图片存储配置
minio:
  endpoint: 47.122.51.163:9000 #TODO
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: activities

# Knife4J配置
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xidian.activities.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn


